"""Run Alembic migrations programmatically.

Usage:
  python scripts/run_migrations.py upgrade head
"""

import sys
from alembic.config import Config
from alembic import command
import os

# Ensure project root is on sys.path so alembic's env.py can import project modules
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))


def main(argv):
    cfg = Config(os.path.join(os.path.dirname(__file__), "..", "alembic.ini"))
    # allow DATABASE_URL override by env var
    cfg.set_main_option(
        "sqlalchemy.url",
        os.environ.get("DATABASE_URL", cfg.get_main_option("sqlalchemy.url")),
    )
    if len(argv) < 1:
        print("Usage: run_migrations.py <alembic-command> [args]")
        return 1
    cmd = argv[0]
    args = argv[1:]
    if cmd == "upgrade":
        command.upgrade(cfg, args[0] if args else "head")
    elif cmd == "downgrade":
        command.downgrade(cfg, args[0] if args else "-1")
    elif cmd == "revision":
        message = args[0] if args else "autogenerated"
        command.revision(cfg, message=message, autogenerate=True)
    else:
        print("Unsupported command", cmd)


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
